interface Language {
  code: string;
  name: string;
  flag: string;
}

const languages: Language[] = [
  { code: "eng", name: "English", flag: "🇬🇧" },
  { code: "spa", name: "Spanish", flag: "🇪🇸" },
  { code: "fre", name: "French", flag: "🇫🇷" },
  { code: "ger", name: "German", flag: "🇩🇪" },
  { code: "ita", name: "Italian", flag: "🇮🇹" },
  { code: "jpn", name: "Japanese", flag: "🇯🇵" },
  { code: "chi", name: "Chinese", flag: "🇨🇳" },
  { code: "rus", name: "Russian", flag: "🇷🇺" },
  { code: "por", name: "Portuguese", flag: "🇵🇹" },
  { code: "swe", name: "Swedish", flag: "🇸🇪" },
  { code: "ara", name: "Arabic", flag: "🇸🇦" },
  { code: "ben", name: "Bengali", flag: "🇧🇩" },
  { code: "hin", name: "Hindi", flag: "🇮🇳" },
  { code: "kor", name: "Korean", flag: "🇰🇷" },
  { code: "pol", name: "Polish", flag: "🇵🇱" },
  { code: "tur", name: "Turkish", flag: "🇹🇷" },
  { code: "vie", name: "Vietnamese", flag: "🇻🇳" },
  { code: "tha", name: "Thai", flag: "🇹🇭" },
  { code: "ukr", name: "Ukrainian", flag: "🇺🇦" },
  { code: "urd", name: "Urdu", flag: "🇵🇰" },
  { code: "nld", name: "Dutch", flag: "🇳🇱" },
  { code: "heb", name: "Hebrew", flag: "🇮🇱" },
  { code: "ind", name: "Indonesian", flag: "🇮🇩" },
  { code: "mal", name: "Malayalam", flag: "🇮🇳" },
  { code: "mar", name: "Marathi", flag: "🇮🇳" },
  { code: "tam", name: "Tamil", flag: "🇮🇳" },
  { code: "tel", name: "Telugu", flag: "🇮🇳" },
  { code: "gre", name: "Greek", flag: "🇬🇷" },
  { code: "fin", name: "Finnish", flag: "🇫🇮" },
  { code: "dan", name: "Danish", flag: "🇩🇰" },
  { code: "nor", name: "Norwegian", flag: "🇳🇴" },
  { code: "ron", name: "Romanian", flag: "🇷🇴" },
  { code: "ces", name: "Czech", flag: "🇨🇿" },
  { code: "hun", name: "Hungarian", flag: "🇭🇺" },
  { code: "bul", name: "Bulgarian", flag: "🇧🇬" },
  { code: "hrv", name: "Croatian", flag: "🇭🇷" },
  { code: "lit", name: "Lithuanian", flag: "🇱🇹" },
  { code: "slk", name: "Slovak", flag: "🇸🇰" },
  { code: "slv", name: "Slovenian", flag: "🇸🇮" },
  { code: "est", name: "Estonian", flag: "🇪🇪" },
  { code: "lav", name: "Latvian", flag: "🇱🇻" },
  { code: "cat", name: "Catalan", flag: "🏴" },
  { code: "glg", name: "Galician", flag: "🏴" },
  { code: "eus", name: "Basque", flag: "🏴" },
  { code: "gle", name: "Irish", flag: "🇮🇪" },
  { code: "gla", name: "Scottish Gaelic", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "cym", name: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "fas", name: "Persian", flag: "🇮🇷" },
  { code: "kaz", name: "Kazakh", flag: "🇰🇿" },
  { code: "swh", name: "Swahili", flag: "🇹🇿" },
  { code: "afr", name: "Afrikaans", flag: "🇿🇦" },
  { code: "amh", name: "Amharic", flag: "🇪🇹" },
  { code: "aze", name: "Azerbaijani", flag: "🇦🇿" },
  { code: "bel", name: "Belarusian", flag: "🇧🇾" },
  { code: "bos", name: "Bosnian", flag: "🇧🇦" },
  { code: "mya", name: "Burmese", flag: "🇲🇲" },
  { code: "khm", name: "Khmer", flag: "🇰🇭" },
  { code: "lat", name: "Latin", flag: "🏴" },
  { code: "mkd", name: "Macedonian", flag: "🇲🇰" },
  { code: "mon", name: "Mongolian", flag: "🇲🇳" },
  { code: "nep", name: "Nepali", flag: "🇳🇵" },
  { code: "san", name: "Sanskrit", flag: "🇮🇳" },
  { code: "sin", name: "Sinhala", flag: "🇱🇰" },
  { code: "sqi", name: "Albanian", flag: "🇦🇱" },
  { code: "tgl", name: "Tagalog", flag: "🇵🇭" },
  { code: "tib", name: "Tibetan", flag: "🏴" },
  { code: "uzb", name: "Uzbek", flag: "🇺🇿" },
  { code: "hau", name: "Hausa", flag: "🇳🇬" },
  { code: "som", name: "Somali", flag: "🇸🇴" },
  { code: "yor", name: "Yoruba", flag: "🇳🇬" },
  { code: "zul", name: "Zulu", flag: "🇿🇦" },
  { code: "mlt", name: "Maltese", flag: "🇲🇹" },
  { code: "ice", name: "Icelandic", flag: "🇮🇸" },
  { code: "srd", name: "Sardinian", flag: "🏴" },
  { code: "bre", name: "Breton", flag: "🏴" },
  { code: "fry", name: "Frisian", flag: "🏴" },
  { code: "vol", name: "Volapük", flag: "🏴" },
  { code: "ido", name: "Ido", flag: "🏴" },
  { code: "epo", name: "Esperanto", flag: "🏴" },
  { code: "que", name: "Quechua", flag: "🇵🇪" },
  { code: "may", name: "Malay", flag: "🇲🇾" },
  { code: "lao", name: "Lao", flag: "🇱🇦" },
];

export function getLanguageInfo(code: string): Language {
  const language = languages.find((lang) => lang.code === code);
  return language || { code, name: code, flag: "🏴" };
}

export function getLanguageDisplay(code: string): string {
  const { name, flag } = getLanguageInfo(code);
  return `${flag} ${name}`;
}
